insert into users (username, password, email) values ( 'AWasasddasdal',
    '$2b$10$JmjFSeVqdLqd5wAlzPnnM.5e82ZsNoH03eRJO1E9jxTjRKKeAHQ4C',
    'andrasasddsadewwal@gmail.com');

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Geranium', 'Pelargonium', 'With more than 300 varieties in Australia, there''s a geranium to suit any garden with a great range of colours, shapes and styles. Most geraniums are low spreading plants, with hairy, hand-shaped leaves. In spring, they bloom into colours ranging from red, white, pink, salmon to dark purple and even black.', 7, 'full sun', 'https://media.prod.bunnings.com.au/api/public/content/06b03979a0374b7e895274a8ce6b9f38?v=fb7384a0&t=w500dpr1', 'both', 10, 365, 100, 'Potting mix, with equal amounts soil, peat moss and perlite.');

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Peace Lily ', 'Spathiphyllum', 'Hardy and very tolerant of low light situations making them ideal interior plants for that darker corner or mass planting where a dramatic foliage effect is needed', 7, 'full shade', 'https://media.prod.bunnings.com.au/api/public/content/bf83ed9c73ca41c78a2b76b98b441513?v=e2a19639&t=w500dpr1', 'indoor', 0, 50, 0, 'Perlite, peat moss, coir or loam.');

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Dwarf Sunflowers', 'Helianthus annuus', 'Bright yellow colours and multiple flower heads, with bright yellow blooms, yet still pollen free', 7, 'full sun', 'https://l.hdnux.com/350x235p/s3-us-west-1.amazonaws.com/contentlab.studiod/getty/0f5989a1a6fb432d9decc048e4013aca.jpg', 'outdoor', 160, 0, 100, 'Fast draining soil mix.');

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Cherry Tomatoes', 'Solanum lycopersicum var. cerasiforme', 'Cherry tomatoes are sweet and spicy and produce a mass of mini roma-shaped fruits throughout the season. Fresh or dried, this tomato is delicious.', 4, 'full sun', 'https://www.gardeningknowhow.com/wp-content/uploads/2009/04/cherry-tomatoes-1-400x274.jpg', 'outdoor', 14, 50, 365, 'Loam and sandy loam soils.');

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Dalina', 'Dahlia Dalina', 'When planted in the garden or in containers, Dahlia Dalinas have excellent ornamental qualities. Each plant will produce an abundance of pom-pom shaped flowers from late spring until autumn.', 4, 'partial', 'https://media.prod.bunnings.com.au/api/public/content/06607144bac44e1885d5be3343a4a319?v=80fc5ad8', 'outdoor', 14, 0, 365, 'Moist, well-drained soil, improved with well-rotted animal manure, leaf litter or compost.');

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Daffodil ', 'Narcissus', 'Easy to grow and ideal for naturalising. Daffodils are the traditional symbol of spring, ideal for the garden, beautiful when planted en masse.', 7, 'partial', 'https://www.proflowers.com/blog/wp-content/uploads/2021/04/daffodil-care-guide-thumb.jpg', 'both', 28, 50, 100, 'Free-draining soil, but adaptable to most types, except wet soils');

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Orange Orchid', 'Orchidaceae', 'Add a pop of orange to your tablescape, it will typically bloom about once a year, for up to three months.', 14, 'partial', 'https://cdn.shopify.com/s/files/1/0150/6262/products/the-sill_petite-orange-orchid_varient_x-small_bryant_cream_768x.png?v=1645215264', 'indoor', 28, 0, 100, 'Coarse potting mix');

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Freesia', 'Freesia', 'Freesias originated in South Africa meaning they have adapted well to that climate. These perennials are most commonly grown from a bulb, which is planted in late summer or early autumn.', 7, 'partial', 'https://www.gardendesign.com/pictures/images/900x705Max/dream-team-s-portland-garden_6/yellow-freesia-flower-yellow-flower-shutterstock-com_14849.jpg', 'both', 28, 0, 100, 'Slightly sandy soil that has been amended with moisture retaining organic material');


insert into user_plant_schedule (user_id, plant_id, plant_nickname, last_watering_date, last_fertilising_date, last_pruning_date, last_repotting_date) values (1, 4, 'Bob', NOW()::timestamptz, NOW()::timestamptz, NOW()::timestamptz, NOW()::timestamptz);

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Native Hydrangea', 'Rousseaceae', 'Abrophyllum ornans is a shrub to small tree to 8 m tall. It is grown mainly for its large shiny leaves and showy fruit. The small greenish-yellow to white, and slightly fragrant flowers appear in showy panicles from October to December. It is a useful edge or pioneer species for rainforest restoration', 1, 'partial', 'https://resources.austplants.com.au/wp-content/uploads/Abrophyllum-ornans.jpg', 'outdoor', 365, 365, 365, 'Hydrangeas thrive in well-draining, organically rich soil, so dig in additional compost and cow manure at planting. They also love moisture, so add some water-retaining crystals to the soil as you backfill. After planting, mulch the surface of the soil to a depth of about 3- 5cm.');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Desert Chinese Lantern', 'Malvaceae', 'Abutilon otocarpum is a small shrub to about 0.7 metres tall, found on the western plains on NSW, in semi-arid conditions; on red sandy soils, sand rises and dunes. It is also found in all other mainland states in similar habitats.', 7, 'full sun', 'https://www.bhg.com.au/media/4146/gettyimages-522259050.jpg?width=720&center=0.0,0.0', 'both', 182, 365, 365, 'Rich, moist, well-drained soil. In pots, use a good-quality potting mix');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Gold Dust Wattle', 'Acacia acinacea', 'Acacia acinacea is a small to medium shrub that is found in south-eastern South Australia, most of Victoria and southern NSW. Phyllodes are small, elliptic with an offset mucro (pointed end). There is a small gland near the centre of the phyllode margin. The flowers are in globular heads with 8-20 flowers in each head. Blooms are bright golden and carried in pairs at the base of each phyllode.', 1, 'full sun', 'https://resources.austplants.com.au/wp-content/uploads/Acacia-acinacea.jpg', 'outdoor', 365, 121, 365, 'Dry, well-draining, fertile soil which can be sandy, clayey, loamy, or poor');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('string-of-pearls', 'Senecio rowleyanus', 'Also known as “string of beads” or “rosary,” this succulent is a perennial vine of the Asteraceae family and is native to southwest Africa. Like most succulents, it requires very little hands-on care. After you have one string of pearls plant, you can easily propagate new ones (or make your original look fuller) by placing cuttings into soil and allowing them to take root.', 14, 'full sun', 'https://www.gardenista.com/ezoimgfmt/media.gardenista.com/wp-content/uploads/2017/01/etsy-countrygardbysparrow-string-of-beads-in-terracotta.png?ezimgfmt=rs:733x487/rscb1/ng:webp/ngcb1', 'both', 42, 182, 365, 'cactus potting mix (sandy)');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Peperomia', 'Peperomia', 'The peperomia plant is a smart choice for beginner houseplant enthusiasts. Not only are they forgiving plants that tolerate some benign neglect, but the spectacular variety of colors and textures available within the species means that you can amass an interesting collection of plants for every style and space, all of which require the same care', 14, 'partial', 'https://www.thespruce.com/thmb/6CqdIcMb2_RbLJlo-zeH5oAIl-Y=/584x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/peperomia-plant-4584414-11-5371969d6c2b43348c72b4bb10320833.jpg', 'both', 365, 365, 365, 'orchid potting mix');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Devils Ivy', 'Epipremnum aureum', 'This houseplant stands out thanks to its heart-shaped satiny leaves with silver, pale green, yellow or whitish spots, or a flame pattern. it’s also a reliable companion: if looked after well, this domestic wonder can grow very old and remain beautiful. The plant also gives something back in return for your loving care: according to the NASA Clean Air Study, Devil’s Ivy is one of the plants that helps improve the air quality in your home.', 14, 'partial', 'https://www.flowercouncil.co.uk/sites/default/files/styles/slideshow/public/w8.scindapsus2018.4.mid_.jpg?itok=au5GNgIZ', 'both', 28, 182, 365, 'a light, porous, aerated and well-drained soil');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Basil', 'Ocimum basilicum', 'The basil herb plant produces aromatic leaves that are commonly used in Italian and Mediterranean dishes. Basil seeds are also a popular Thai ingredient.
Because basil is an annual, it grows extremely quickly. In fact, it can go from seed to harvest in as little as 3 to 4 weeks. This quick and easy-growing herb is an excellent choice for beginner gardeners.', 7, 'full sun', 'https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fit,w_696,h_1066/k%2Farchive%2Fcc7ce5adb68b5932d8aa6c7a256aa7344625ede4', 'both', 14, 21, 365, 'Well-drained, moist soil with a neutral pH.');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Flat leaf parsley', 'Petroselinum crispum', 'Grown for its superior flavour and culinary attributes, Italian flat leaf parsley is versatile in the kitchen and contains a powerhouse of nutrients', 2, 'full sun', 'https://media.prod.bunnings.com.au/api/public/content/1ec47e4906d0402084a81a2b8363a0b7?v=8d9270d2&t=w1300dpr1', 'both', 182, 14, 182, 'plant in a soil enriched with compost and aged manure.');

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Chives', 'Allium schoenoprasum', 'Chives are a low maintenance, easy to grow perennial herb, grown for their onion-scented tasting leaves. These are a delicious addition to salads, and can be added to many other savoury dishes.', 4, 'partial', 'https://www.lovethegarden.com/sites/default/files/content/articles/UK_chives-growing.jpg', 'both', 185, 4, 365, 'Chalky, Clay, Loamy, Sandy');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Thyme', 'Thymus vulgaris', 'Thyme is a kitchen garden staple thats easy to grow, virtually maintenance free, and makes an ideal drought-tolerant edible ground cover.', 14, 'full sun', 'https://media.prod.bunnings.com.au/api/public/content/bba6be9218c14468836652ba9de7e36f?v=6ddf5519&t=w1300dpr1', 'outdoor', 182, 365, 365, 'A free-draining garden soil enriched with compost and well-aged manure.

');

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Lemmon tree', 'Citrus limon', 'A beautiful landscape tree that also produces masses of incredibly delicious and useful fruit, a lemon tree can be an awesome addition to your garden.', 14, 'full sun', 'https://balconygardenweb-lhnfx0beomqvnhspx.netdna-ssl.com/wp-content/uploads/2015/05/How-to-Grow-a-Lemon-Tree-in-Pot.jpg', 'outdoor', 42, 365, 730, 'The ideal soil is a rich, well-drained loam, however the lemon tree is adaptable to almost any soil type, except heavy clay.');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Lime tree', 'Citrus x aurantiifolia', 'The juicy fruit may be too astringent to enjoy on its own, but it’s the perfect ingredient for adding a refreshing zing or a sharp tang to curries, drinks and desserts.', 14, 'full sun', 'https://media.prod.bunnings.com.au/api/public/content/ad9f80c20577466686a68d1b4ba2c554?v=e75b8a2d&t=w800dpr1', 'outdoor', 42, 365, 730, 'fairly tolerant of most soil types, but it needs to be rich and well-draining.
');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Rosemary', 'Salvia rosmarinus', 'Rosemary, is a shrub with fragrant, evergreen, needle-like leaves and white, pink, purple, or blue flowers, native to the Mediterranean region.', 14, 'full sun', 'https://www.gardenerreport.com/wp-content/uploads/2020/06/0_0_InShot_20200616_210713668.jpg', 'outdoor', 365, 84, 365, 'Plant in a well-drained soil that’s neutral to slightly alkaline. Add dolomite or lime at least once a year to increase the pH level and keep the herb happy.');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Carrot', 'Daucus carota var. sativus', 'Carrots are a fun vegie for you or the kids to grow because when the time comes to harvest, it’s like pulling up buried treasure! There are so many different varieties to choose from, including baby, purple, yellow and even round carrots! They can be used in so many ways – eaten crunchy and fresh on their own or mixed into yummy salads or baked until they are tender and delicious.', 2, 'full sun', 'https://media.prod.bunnings.com.au/api/public/content/81fc527f2a77473694d35eff97725800?v=290da8aa&t=w800dpr1', 'outdoor', 28, 0, 0, 'Must have a very loose and open soil for the large storage root to develop well.');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Chilli pepper', 'Capsicum frutescens', 'Chili peppers are varieties of the berry-fruit of plants which are members of the nightshade family Solanaceae, cultivated for their pungency. Chili peppers are widely used in many cuisines as a spice to add heat to dishes. Capsaicin and related compounds known as capsaicinoids are the substances giving chili peppers their intensity when ingested or applied topically.', 3, 'full sun', 'https://media.prod.bunnings.com.au/api/public/content/1e3fa47963c64f38b795b35f399db948?v=8628e49c&t=w800dpr1', 'outdoor', 365, 365, 365, 'Free-draining quality garden soil or potting mix. Doesnt grow well in heavy clay, damp or wet soils.');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('bird of paradise', 'strelitzia nicolai', 'Hardy, easy to grow and architecturally dramatic with some of the most stunning and bizarre flowers you will ever see.', 4, 'partial', 'https://media.prod.bunnings.com.au/api/public/content/5775ce61580144de8e621e7085ba69f4?v=5fb8fcc7&t=w1100dpr1', 'both', 365, 0, 365, 'Light, free-draining with additional compost at planting time.

');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Radish', 'Raphanus sativus', 'Radish is an annual or biennial plant in the mustard family, grown for its large succulent taproot. The common radish is likely of Asian or Mediterranean origin and is cultivated worldwide. Radish roots are low in calories and are usually eaten raw, the young leaves can be cooked like spinach. ', 2, 'full sun', 'https://media.prod.bunnings.com.au/api/public/content/7e81e4d1f3ba42a5a2e25138e8a77b95?v=8b2e843c&t=w800dpr1', 'outdoor', 0, 0, 0, 'loose, well-drained soil enriched with organic matter. In pots, use a quality potting mix.');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Coriander', 'Coriandrum sativum', 'Coriander is an annual herb. It is also known as Chinese parsley, dhania, or cilantro.All parts of the plant are edible, but the fresh leaves and the dried seeds (as a spice) are the parts most traditionally used in cooking.', 4, 'partial', 'https://www.gardeningknowhow.com/wp-content/uploads/2009/01/potted-coriander-400x300.jpg',  'both', 28, 0, 0, 'Performs well in most soils but dislikes clay and will not tolerate waterlogging.');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Bacopa', 'Sutera cordata', 'The delicate pastel flowers and finely textured foliage of bacopa plants belie its tough nature. Most often grown as an annual, this blooming workhorse provides summer-long color with very little effort. Whether used as a cascading accent in a hanging basket or a sprawling ground cover in the landscape, bacopa combines well with other plants and is virtually carefree, making it a versatile choice for home gardeners.', 4, 'partial', 'https://www.gardendesign.com/pictures/images/320x240Exact_0x46/site_3/giant-snowflake-bacopa-small-white-flower-sutera-cordata-proven-winners_15054.jpg', 'both', 14, 0, 365, 'For pots, use a high quality all-purpose potting soil that drains well.');

insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Zygocactus', 'Schlumbergera truncata', 'Zygocactus is a small genus of cacti with six to nine species found in the coastal mountains of south-eastern Brazil. These plants grow on trees or rocks in habitats that are generally shady with high humidity, and can be quite different in appearance from their desert-dwelling cousins. Most species of Zygocactus have stems which resemble leaf-like pads joined one to the other and flowers which appear from areoles at the joints and tips of the stems. Two species have cylindrical stems more similar to other cacti.', 14, 'partial', 'https://pics.davesgarden.com/pics/2003/12/21/htop/83ec6e.jpg', 'both', 182, 0, 365, ' Zygocactus need good drainage and grow better in pots or hanging baskets rather than in the ground. You can often get away with using normal potting mix but ideally a cacti or orchid potting mix is better because they have extra drainage.');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Snap dragon', 'Antirrhinum majus', 'Snapdragons are named so because of the flowers fancied resemblance to the face of a dragon that opens and closes its mouth when laterally squeezed. They are native to rocky areas of Europe, the United States, Canada, and North Africa.', 3, 'full sun', 'https://www.australianseed.com/persistent/catalogue_images/products/snapdragon-giant-tetra.jpg', 'both', 182, 182, 365, 'Snapdragons will do best in well-draining soil, with plenty of organic matter.');


insert into plants (name, latin_name, description, watering_frequency_in_days, sunlight, image_url, plant_location, fertilising_frequency_in_days, pruning_frequency_in_days, repotting_frequency_in_days, soil_type) values ('Birds nest fern', 'Asplenium antiquum nidus var plicatum ', 'Medium-large fern with long fronds, each distinctly frilled and rippled on the edges like a sheet of fancy lasagna.', 4, 'partial', 'https://www.flowerpower.com.au/media/catalog/product/9/0/9005020140.jpg', 'both', 28, 0, 365, 'These plants like soil that’s loose and rich in organic matter with excellent drainage. A peat-based potting mix is good for container plants.');